### ISSUE TITLE
被禁用了？😨

### ISSUE THREAD

**Issue by 1357310795** [PhotonQuantum/shuiyuan-archiver#10]
![image](https://user-images.githubusercontent.com/35869804/203036031-e9a8f7e7-dd9c-4699-ba62-4e5a6da6327e.png)
![image](https://user-images.githubusercontent.com/35869804/203036053-b696bffd-078f-4dd8-b640-65f816233008.png)

**Comment by PhotonQuantum** [comment]
没吧，我刚才测试了一下好像没有问题，是不是没复制全（

**Comment by 1357310795** [comment]
肯定复制全了。之前一直能用的，今天打开突然要授权，怀疑是什么接口有变动

**Comment by PhotonQuantum** [comment]
是的，我也发现要重新授权，不过授权之后是能正常使用的

**Comment by 1357310795** [comment]
解决了
![image](https://user-images.githubusercontent.com/35869804/203038029-aa79e503-bd35-4d6f-a1e6-8a0a7b11c523.png)
把我这些回车全部删掉，就授权成功了
![FE@_9J ~ K%WRL6YPVY{6MK](https://user-images.githubusercontent.com/35869804/203038113-5d00e857-5403-433d-b285-d20558513324.png)
***
那应该是代码有点问题（

**Comment by PhotonQuantum** [comment]
草 我看看能不能改进一下（

**Comment by 1357310795** [comment]
补充：是换行不是回车

![image](https://user-images.githubusercontent.com/35869804/203038603-c5b6e9dd-c302-4f56-b2ef-65c4342e5943.png)

**Comment by 1357310795** [comment]
好像还是不太对劲

检查过网络（校园网）和代理设置（没开代理），没有问题

![image](https://user-images.githubusercontent.com/35869804/203041111-914dbae5-e598-488d-97d9-2a1944cbf07c.png)

**Comment by PhotonQuantum** [comment]
思考 看看连上 sjtu vpn 是不是正常 我是在寝室试的

**Comment by 1357310795** [comment]
可以了，谢谢！
***
说起来这个工具走的啥协议啊，抓包工具一点都抓不到

**Comment by PhotonQuantum** [comment]
奇怪 走的是 https 啊 而且 tls 用的也是系统的证书

**Comment by PhotonQuantum** [comment]
暂时先关闭这个 issue 了，如果有问题的话可以再次打开
