### ISSUE TITLE
存档失败：bytes stream stuck

### ISSUE THREAD

**Issue by 1357310795** [PhotonQuantum/shuiyuan-archiver#19]
https://shuiyuan.sjtu.edu.cn/t/topic/12642

![image](https://github.com/PhotonQuantum/shuiyuan-archiver/assets/35869804/eaa03426-0934-4648-949d-03634de395e2)

**Comment by PhotonQuantum** [comment]
bytes stream stuck 一般是网络卡住造成的，连续一段时间完全没有下载任何东西就会触发，重试应该就会正常

**Comment by PhotonQuantum** [comment]
我这边存档成功了，无法复现
是在使用最新的版本吗？之前的一些版本确实有一个会造成异常 stuck 的 bug

**Comment by 1357310795** [comment]
哦，最新版存成功了，看来是我的问题🤣
