### ISSUE TITLE
自定义表情显示异常

### ISSUE THREAD

**Issue by 1357310795** [PhotonQuantum/shuiyuan-archiver#3]
![image](https://user-images.githubusercontent.com/35869804/170653535-914ab3aa-a493-4bb0-8371-3722fb3c314f.png)
![image](https://user-images.githubusercontent.com/35869804/170653583-810e5db2-8939-4803-b8c8-3f86cb671d38.png)

**Comment by PhotonQuantum** [comment]
请问能否提供相关贴子的链接？

**Comment by 1357310795** [comment]
> 请问能否提供相关贴子的链接？

比如 https://shuiyuan.sjtu.edu.cn/t/topic/69916 ，#11
![image](https://user-images.githubusercontent.com/35869804/171084850-4f353732-1ddd-4e6c-8638-45e2926e157f.png)

![image](https://user-images.githubusercontent.com/35869804/171085069-f1e48f09-f0fa-4762-93db-767aa78b2ae3.png)

![image](https://user-images.githubusercontent.com/35869804/171085089-f2df8319-c89d-431a-8665-06136f59b57f.png)


系统：Win 10 21H1
软件版本：v0.3.2
浏览器：Microsoft Edge 101.0.1210.53 (正式版本) (64 位)

**Comment by PhotonQuantum** [comment]
Fixed in https://github.com/PhotonQuantum/shuiyuan-archiver/commit/710fd44cbdd5eabeda752dcab1b553bccf5e8cc4
