### ISSUE TITLE
能否恢复使用相对路径🥺

### ISSUE THREAD

**Issue by 1357310795** [PhotonQuantum/shuiyuan-archiver#4]
在v0.3.1版本中，头像图片使用了相对路径。
![QQ截图20220622194036](https://user-images.githubusercontent.com/35869804/175020664-7b4d5397-f52c-4fd3-90e3-09cb5b0fc427.png)

而在v0.3.3版本中，头像图片使用了本地绝对路径。一旦更换文件夹位置，图片将不能正常显示。
![QQ截图20220622194044](https://user-images.githubusercontent.com/35869804/175020678-bcd41f17-c893-463b-9833-1c7f02aee022.png)

**Comment by PhotonQuantum** [comment]
抱歉，这是个意外的修改，马上修正

**Comment by 1357310795** [comment]
0.3.5版本，用户第二次在帖子内出现时，头像图片仍为绝对路径

![image](https://user-images.githubusercontent.com/35869804/186085618-9e067870-99d4-4dba-be47-e125822eaf5c.png)

**Comment by 1357310795** [comment]
> 0.3.5版本，用户第二次在帖子内出现时，头像图片仍为绝对路径
> 
> ![image](https://user-images.githubusercontent.com/35869804/186085618-9e067870-99d4-4dba-be47-e125822eaf5c.png)

@PhotonQuantum

**Comment by PhotonQuantum** [comment]
Reopening due to reported regression

**Comment by PhotonQuantum** [comment]
已经发布 v0.3.6，应该已经彻底修复了相关问题，能否帮忙尝试一下？

**Comment by 1357310795** [comment]
应该是修好了😘
