### ISSUE TITLE
svg 头像问题

### ISSUE THREAD

**Issue by 1357310795** [PhotonQuantum/shuiyuan-archiver#6]
### 问题描述
>[v0.3.2](https://github.com/PhotonQuantum/shuiyuan-archiver/releases/tag/v0.3.2)
>支持 svg 头像

然而牛排的头像出错了……

下载的是svg
![image](https://user-images.githubusercontent.com/35869804/189328850-65989124-ef2b-4d77-b5e0-31f25989475d.png)

html里面用的是png
![image](https://user-images.githubusercontent.com/35869804/189328921-93a6b668-7c99-4f34-b7c3-1f1aa98d591e.png)

### 版本号
v0.3.6 Windows

**Comment by PhotonQuantum** [comment]
已经在 v0.3.7 修复
