### ISSUE TITLE
不同肤色的表情支持

### ISSUE THREAD

**Issue by 1357310795** [PhotonQuantum/shuiyuan-archiver#8]
抱歉又来打扰了😇
***
![image](https://user-images.githubusercontent.com/35869804/191388770-489787e2-d36a-4350-8a00-3818ab8a389e.png)
![image](https://user-images.githubusercontent.com/35869804/191388822-4a20fb5b-2cf9-4ff9-be08-a1987bf93183.png)

**Comment by PhotonQuantum** [comment]
抱歉最近比较忙，有空一定😂

**Comment by 1357310795** [comment]
好耶，量子姐姐辛苦了！

**Comment by PhotonQuantum** [comment]
想问一下有没有具体贴子的地址方便测试？

**Comment by 1357310795** [comment]
哈哈，找个老帖贴点表情就行

https://shuiyuan.sjtu.edu.cn/t/topic/52317
